### ISSUE TITLE
Can't Install Version 2.6.1

### ISSUE THREAD

**Issue by Loxatan** [i10b/simplematrixbotlib#135]
Hi, I have the problem that I need the version 2.6.1 for the Matrix Registration Bot.
However, it only installs version 2.1.0 for me via `pip install simplematrixbotlib`.
If I try it with `pip install simplematrixbotlib==2.6.1 
`I get:
```
(env) root@vmd76330:~/synapse# pip install simplematrixbotlib==2.6.1
ERROR: Could not find a version that satisfies the requirement simplematrixbotlib==2.6.1 (from versions: 0.0.1, 0.0.2, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 2.0.0, 2.1.0)
ERROR: No matching distribution found for simplematrixbotlib==2.6.1
```

I have set up a Matrix Server after introduction.
I have already updated to Python version 3.9.1, however I'm not quite sure if pip even takes the right version.

Since I'm new to the whole topic, I'm having a bit of trouble troubleshooting

Since the whole problem occurred during the installation or at the start of the registration bot, I have already opened a ticket there.

There we found out that it must be due to the installed version 2.1.0.
However, I just can't get it to version 2.6.1.

https://github.com/moan0s/matrix-registration-bot/issues/2

```
**Desktop (please complete the following information):**
 - OS: Debian 10
(env) root@vmd76330:~/synapse# pip show pip
Name: pip
Version: 22.0.3
Location: /root/synapse/env/lib/python3.7/site-packages
```

Is maybe the Location the problem? But i dont got /python3.9/ ....

Unfortunately, I don't know what all is needed for troubleshooting. If there is any info missing, please let me know.

**Comment by KrazyKirby99999** [comment]
You are using Python 3.7, while Python 3.8 or higher is required. Have you tried using `python3.9` as the command instead of `python`/`python3`?

**Comment by KrazyKirby99999** [comment]
Is your problem resolved?

**Comment by KrazyKirby99999** [comment]
Closed due to lack of response.
