### ISSUE TITLE
Send messages as bot instead of as user

### ISSUE THREAD

**Issue by benthetechguy** [i10b/simplematrixbotlib#142]
**Is your feature request related to a problem? Please describe.**
There are two ways to send a message in Matrix, as a bot or as a user. In Element, messages sent from bots appear grey, while messages sent from users appear black or white depending on the theme. I noticed that my bot made with this library has its messages sent as a user instead of as a bot, even though this library is specifically for creating bots.

**Describe the solution you'd like**
Send messages as a bot, since the library is built for bots.

**Comment by imbev** [comment]
Can you provide screenshots?

**Comment by benthetechguy** [comment]
Notice how my message is white and the bot's response is grey:
![image](https://user-images.githubusercontent.com/29379327/180660825-c9690acc-490f-4d7e-9403-1c24291d4c09.png)
Here's what it looks like under light theme:
![image](https://user-images.githubusercontent.com/29379327/180660888-87a62697-bb10-4a19-b6aa-19ffadd6c445.png)
That was back when I used maubot. Now with simplematrixbotlib, the response would also be white, as if I logged into the bot account on a normal Matrix client and sent it myself.

**Comment by imbev** [comment]
What maubot method were you using to send the messages?

**Comment by benthetechguy** [comment]
Not sure, I was just using the [reactbot](https://github.com/maubot/reactbot) plugin.

**Comment by imbev** [comment]
Can you send me the Matrix event sources of one of the events of each bot?

**Comment by benthetechguy** [comment]
How can I get that info?

**Comment by imbev** [comment]
With the element client, hover over the message,  click options, click view source

**Comment by benthetechguy** [comment]
maubot:
```json
{
  "content": {
    "body": "AMD Drivers: https://amd.com/en/support\nnVidia Drivers: https://nvidia.com/Download/index.aspx\nRealtek Drivers: https://www.realtek.com/en/downloads\n",
    "msgtype": "m.notice"
  },
  "origin_server_ts": 1631627945225,
  "room_id": "!EWPxWFbOucPMmdTsdh:privacytools.io",
  "sender": "@tscbot:envs.net",
  "type": "m.room.message",
  "unsigned": {
    "age": 455978308
  },
  "event_id": "$90IWsiNs_b9TQPQtcwcAjcGQYvFD5UPwyYDN4I4GJXM",
  "user_id": "@tscbot:envs.net",
  "age": 455978308
}
```
simplematrixbotlib:
```json
{
  "content": {
    "body": "I have been online for 29 seconds.",
    "msgtype": "m.text"
  },
  "origin_server_ts": 1655699752643,
  "room_id": "!qBaeEuoSHSgyUrBQeq:fairydust.space",
  "sender": "@tscbot:envs.net",
  "type": "m.room.message",
  "unsigned": {},
  "event_id": "$mHF_onBgHz_i4cMix8b_2yHZGWcaL3rHDbXPjqAjk3o",
  "user_id": "@tscbot:envs.net"
}
```
I think the magic field here is `"msgtype": "m.notice"`.

**Comment by imbev** [comment]
Could you try using the `send_markdown_message method` as shown in https://simple-matrix-bot-lib.readthedocs.io/en/latest/manual.html#using-the-send-markdown-message-method ?

**Comment by imbev** [comment]
Will be closed soon unless a response is sent.

**Comment by benthetechguy** [comment]
Yes, sorry. It seems the previous reply went to my spam folder and I didn't see it. That method worked.
